apiVersion: v1
kind: Secret
metadata:
  name: {{ include "code-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "code-server.name" . }}
type: Opaque
data:
  {{ if .Values.password }}
  password: "{{ .Values.password | b64enc }}"
  {{ else }}
  password: "{{ randAlphaNum 24 | b64enc }}"
  {{ end }}
