{{- if or .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ include "code-server.name" . }}
  name: {{ template "code-server.serviceAccountName" . }}
{{- end -}}
